package py.com.ventu.app;

import static java.awt.event.KeyEvent.VK_ENTER;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import py.com.ventu.controladores.UsuarioJpaController;
import py.com.ventu.entidades.Usuario;

/**
 * @author carlitox
 */
public class Login extends javax.swing.JDialog {

    //Logger logger = Logger.getLogger("log");  
    // FileHandler fh;  
    private EntityManager em;
    private UsuarioJpaController service;
    private Usuario usuarioLogueado;
    Logger log;
    private boolean estado = false;

    public Login() {
        initComponents();
    }

    public Login(java.awt.Frame parent, boolean modal, EntityManager em, Logger logger) {
        super(parent, modal);
        initComponents();

        this.em = em;
        this.log = logger;
        service = new UsuarioJpaController(em);
    }

    public Login(EntityManager em) {
        initComponents();

        this.em = em;
        service = new UsuarioJpaController(em);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        cmdAceptar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();

        setTitle("Acceso al Sistema");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Usuario:");

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUsuario.setToolTipText("Nombre de usuario para acceso al sistema");
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Contraseña:");

        txtContrasena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtContrasena.setToolTipText("Contraseña válida para ingreso al sistema");
        txtContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContrasenaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(txtContrasena))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        cmdAceptar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/com/ventu/imagenes/seleccionar_16.png"))); // NOI18N
        cmdAceptar.setText("Aceptar");
        cmdAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAceptarActionPerformed(evt);
            }
        });

        cmdCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/py/com/ventu/imagenes/quitar_16.png"))); // NOI18N
        cmdCancelar.setText("Cancelar");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(cmdCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancelar)
                    .addComponent(cmdAceptar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void cmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAceptarActionPerformed
        validar();
    }//GEN-LAST:event_cmdAceptarActionPerformed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (evt.getKeyCode() == VK_ENTER) {
            validar();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContrasenaKeyPressed
        if (evt.getKeyCode() == VK_ENTER) {
            validar();
        }
    }//GEN-LAST:event_txtContrasenaKeyPressed

    public boolean getEstado() {
        return estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    public Usuario getUsuarioLogueado() {
        return usuarioLogueado;
    }

    public void setUsuarioLogueado(Usuario user) {
        this.usuarioLogueado = user;
    }

    public void validar() {
        if (!this.txtUsuario.getText().isEmpty()
                && !this.txtContrasena.getText().isEmpty()) {
            try {
                //recuperar el usuario ingresado
                Usuario user = (Usuario) service.buscarUsuariosPorUsuario(this.txtUsuario.getText());

                if (user != null && user.getContrasena().equals(this.txtContrasena.getText())) {
                    this.setUsuarioLogueado(user);
                    this.setEstado(true);
                    this.setVisible(false);
                    this.dispose();

                   // log.info("NUEVO INICIO DE SESSION DE: " + user.getNombre());

                    /*try {  
                     fh = new FileHandler("../sgf.log");
                     logger.addHandler(fh);
                     SimpleFormatter formatter = new SimpleFormatter();  
                     fh.setFormatter(formatter);  

                     // the following statement is used to log any messages  
                     logger.info("INICIO DE SESSION DE: " + user.getNombre());
                     } catch (IOException ex) {
                     Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                     } catch (SecurityException ex) {
                     Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                     }
                     */
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario o contraseña ingresados no son válidos.",
                            "Acceso al Sistema", JOptionPane.ERROR_MESSAGE);
                    valoresDefecto();
                }

            } catch (HibernateException e) {
                JOptionPane.showMessageDialog(null, "Error al iniciar sesión en el sistema.",
                        "Acceso al Sistema", JOptionPane.ERROR_MESSAGE);
                valoresDefecto();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar el usuario y contraseña para iniciar sesión en el sistema.",
                    "Acceso al Sistema", JOptionPane.ERROR_MESSAGE);
            valoresDefecto();
        }
    }

    public void valoresDefecto() {
        this.estado = false;
        this.txtUsuario.setText("");
        this.txtContrasena.setText("");
        this.txtUsuario.grabFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAceptar;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
