package py.com.ventu.app;

import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

import py.com.ventu.bootstrap.SGFBoostrap;
import py.com.ventu.app.mantenimiento.FrmClientes;
import py.com.ventu.app.mantenimiento.FrmConfiguracion;
import py.com.ventu.app.mantenimiento.FrmProductos;
import py.com.ventu.app.mantenimiento.FrmTipoProductos;
import py.com.ventu.app.ventas.FrmControlCaja;
import py.com.ventu.app.ventas.FrmVentas;
import py.com.ventu.entidades.Usuario;

/**
 * @author cpatino
 */
public class Principal extends javax.swing.JFrame {

    private EntityManagerFactory emf;
    private EntityManager em;
    private Usuario usuario;

    // para la carga default del sistema
    private SGFBoostrap boot;

    Logger logger = Logger.getLogger("log");
    FileHandler fh;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        iniciarSesion();

        try {
            boot = new SGFBoostrap(em);
        } catch (Exception e) {
            e.printStackTrace();
        }

        iniciarLog();
        bloquearMenus();
        login();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSistema = new javax.swing.JMenu();
        mnuIniciarSesion = new javax.swing.JMenuItem();
        mnuCerrarSesion = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenu();
        mnuVentasFacturacion = new javax.swing.JMenuItem();
        mnu_ajuste_stock = new javax.swing.JMenuItem();
        mnuInformes = new javax.swing.JMenu();
        mnuListadoStock = new javax.swing.JMenuItem();
        mnuReposicionDiaria = new javax.swing.JMenuItem();
        mnuVentasPorVendedor = new javax.swing.JMenuItem();
        mnuEstadoCuentaClientes = new javax.swing.JMenuItem();
        mnuInfGerenciales = new javax.swing.JMenu();
        mnuInformes_controlCaja = new javax.swing.JMenuItem();
        mnuInformes_estadisiticas = new javax.swing.JMenuItem();
        mnuEstadiRanking = new javax.swing.JMenuItem();
        mnuDatos = new javax.swing.JMenu();
        mantMnuClientes = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenuItem();
        mnuTipoProductos = new javax.swing.JMenuItem();
        mnuConfiguracion = new javax.swing.JMenu();
        mnu_configuracion = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnu_acerca = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión Comercial - Desarrollado por Carlos Patiño");
        setName("frmPrincipal"); // NOI18N

        escritorio.setToolTipText("");
        escritorio.setFocusable(false);

        mnuSistema.setText("Sistema   ");

        mnuIniciarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuIniciarSesion.setText("Iniciar Sesión");
        mnuIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIniciarSesionActionPerformed(evt);
            }
        });
        mnuSistema.add(mnuIniciarSesion);

        mnuCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mnuCerrarSesion.setText("Cerrar Sesión");
        mnuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarSesionActionPerformed(evt);
            }
        });
        mnuSistema.add(mnuCerrarSesion);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuSistema.add(mnuSalir);

        jMenuBar1.add(mnuSistema);

        mnuVentas.setText("Ventas   ");

        mnuVentasFacturacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuVentasFacturacion.setText("Ventas");
        mnuVentasFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentasFacturacionActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuVentasFacturacion);

        mnu_ajuste_stock.setText("Ajuste de Stock");
        mnu_ajuste_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_ajuste_stockActionPerformed(evt);
            }
        });
        mnuVentas.add(mnu_ajuste_stock);

        jMenuBar1.add(mnuVentas);

        mnuInformes.setText("Informes   ");

        mnuListadoStock.setText("Listado Stock");
        mnuListadoStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListadoStockActionPerformed(evt);
            }
        });
        mnuInformes.add(mnuListadoStock);

        mnuReposicionDiaria.setText("Reposición Diaría");
        mnuReposicionDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReposicionDiariaActionPerformed(evt);
            }
        });
        mnuInformes.add(mnuReposicionDiaria);

        mnuVentasPorVendedor.setText("Ventas por Vendedor");
        mnuVentasPorVendedor.setToolTipText("");
        mnuVentasPorVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentasPorVendedorActionPerformed(evt);
            }
        });
        mnuInformes.add(mnuVentasPorVendedor);

        mnuEstadoCuentaClientes.setText("Estado de Cuenta Clientes");
        mnuEstadoCuentaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEstadoCuentaClientesActionPerformed(evt);
            }
        });
        mnuInformes.add(mnuEstadoCuentaClientes);

        jMenuBar1.add(mnuInformes);

        mnuInfGerenciales.setText("Informes Gerenciales   ");

        mnuInformes_controlCaja.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuInformes_controlCaja.setText("Control de Caja");
        mnuInformes_controlCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInformes_controlCajaActionPerformed(evt);
            }
        });
        mnuInfGerenciales.add(mnuInformes_controlCaja);

        mnuInformes_estadisiticas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuInformes_estadisiticas.setText("Estadisticas Generales");
        mnuInformes_estadisiticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInformes_estadisiticasActionPerformed(evt);
            }
        });
        mnuInfGerenciales.add(mnuInformes_estadisiticas);

        mnuEstadiRanking.setText("Estadisticas y Rankings");
        mnuEstadiRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEstadiRankingActionPerformed(evt);
            }
        });
        mnuInfGerenciales.add(mnuEstadiRanking);

        jMenuBar1.add(mnuInfGerenciales);

        mnuDatos.setText("Datos   ");

        mantMnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mantMnuClientes.setText("Clientes");
        mantMnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantMnuClientesActionPerformed(evt);
            }
        });
        mnuDatos.add(mantMnuClientes);

        mnuProductos.setText("Productos");
        mnuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosActionPerformed(evt);
            }
        });
        mnuDatos.add(mnuProductos);

        mnuTipoProductos.setText("Tipo de Productos");
        mnuTipoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTipoProductosActionPerformed(evt);
            }
        });
        mnuDatos.add(mnuTipoProductos);

        jMenuBar1.add(mnuDatos);

        mnuConfiguracion.setText("Configuración   ");

        mnu_configuracion.setText("Configuración General");
        mnu_configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_configuracionActionPerformed(evt);
            }
        });
        mnuConfiguracion.add(mnu_configuracion);

        jMenuBar1.add(mnuConfiguracion);

        mnuAyuda.setText("Ayuda");

        mnu_acerca.setText("Acerca...");
        mnu_acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_acercaActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnu_acerca);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1113, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("KARU - Sistema de Gestión Comercial");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        int seleccion = JOptionPane.showOptionDialog(
                null, "Está seguro que desea salir del sistema?", "Salir del Sistema",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, // null para icono por defecto.
                new Object[]{"Salir", "Cancelar"}, "Cancelar");
        if (seleccion == 0) {
            em.close();
            System.exit(0);
        }
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mantMnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantMnuClientesActionPerformed
        FrmClientes cliente = new FrmClientes(em, escritorio, usuario);
        escritorio.add(cliente);
        cliente.show();
    }//GEN-LAST:event_mantMnuClientesActionPerformed

    private void mnuIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIniciarSesionActionPerformed
        login();
    }//GEN-LAST:event_mnuIniciarSesionActionPerformed

    private void mnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarSesionActionPerformed
        if (cerrarVentanas()) {
            bloquearMenus();
        }
    }//GEN-LAST:event_mnuCerrarSesionActionPerformed

    private void mnuTipoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTipoProductosActionPerformed
        FrmTipoProductos tipPro = new FrmTipoProductos(em, usuario);
        escritorio.add(tipPro);
        tipPro.show();
    }//GEN-LAST:event_mnuTipoProductosActionPerformed

    private void mnuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosActionPerformed
        if (usuario.getEsAdmin()) {
            FrmProductos prod = new FrmProductos(em, escritorio, usuario);
            escritorio.add(prod);
            prod.show();
        } else {
            JOptionPane.showMessageDialog(null, "Este usuario no tiene permitido el acceso a este módulo. ",
                    "Acceso Denegado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnuProductosActionPerformed

    private void mnuVentasFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentasFacturacionActionPerformed
        FrmVentas ve = new FrmVentas(em, usuario, logger);
        escritorio.add(ve);
        ve.show();
    }//GEN-LAST:event_mnuVentasFacturacionActionPerformed

    private void mnu_acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_acercaActionPerformed
        Acerca acerca = new Acerca(em);
        escritorio.add(acerca);
        acerca.show();
    }//GEN-LAST:event_mnu_acercaActionPerformed

    private void mnu_configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_configuracionActionPerformed
        if (usuario.getEsAdmin()) {
            FrmConfiguracion conf = new FrmConfiguracion(em, usuario);
            escritorio.add(conf);
            conf.show();
        } else {
            JOptionPane.showMessageDialog(null, "Este usuario no tiene permitido el acceso a este módulo. ",
                    "Acceso Denegado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnu_configuracionActionPerformed

    private void mnuInformes_controlCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInformes_controlCajaActionPerformed
        FrmControlCaja cc = new FrmControlCaja(em, usuario, logger);
        escritorio.add(cc);
        cc.show();
    }//GEN-LAST:event_mnuInformes_controlCajaActionPerformed

    private void mnuListadoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListadoStockActionPerformed

    }//GEN-LAST:event_mnuListadoStockActionPerformed

    private void mnuReposicionDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReposicionDiariaActionPerformed
  
    }//GEN-LAST:event_mnuReposicionDiariaActionPerformed

    private void mnuVentasPorVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentasPorVendedorActionPerformed

    }//GEN-LAST:event_mnuVentasPorVendedorActionPerformed

    private void mnuEstadoCuentaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEstadoCuentaClientesActionPerformed
       
    }//GEN-LAST:event_mnuEstadoCuentaClientesActionPerformed

    private void mnuInformes_estadisiticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInformes_estadisiticasActionPerformed
      
    }//GEN-LAST:event_mnuInformes_estadisiticasActionPerformed

    private void mnuEstadiRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEstadiRankingActionPerformed
     
    }//GEN-LAST:event_mnuEstadiRankingActionPerformed

    private void mnu_ajuste_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_ajuste_stockActionPerformed
 
    }//GEN-LAST:event_mnu_ajuste_stockActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuarioLogueado) {
        this.usuario = usuarioLogueado;
    }

    public void iniciarSesion() {
        try {
            emf = Persistence.createEntityManagerFactory("DATAPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al establecer conexión con la base de datos. "
                    + "\n" + e.getMessage() + "\n" + e.getCause(),
                    "Error de conexión", JOptionPane.ERROR_MESSAGE);
            logger.info("Error al establecer conexión con la base de datos. " + "\n" + e.getMessage() + "\n" + e.getCause());
        }
    }

    public void habilitarMenus() {
        this.mnuIniciarSesion.setEnabled(false);
        this.mnuCerrarSesion.setEnabled(true);

        this.mnuDatos.setEnabled(true);
        this.mnuConfiguracion.setEnabled(true);
        this.mnuVentas.setEnabled(true);
        this.mnuInformes.setEnabled(true);
        this.mnuInfGerenciales.setEnabled(true);
    }

    public void bloquearMenus() {
        this.mnuIniciarSesion.setEnabled(true);
        this.mnuCerrarSesion.setEnabled(false);

        this.mnuDatos.setEnabled(false);
        this.mnuConfiguracion.setEnabled(false);
        this.mnuVentas.setEnabled(false);
        this.mnuInformes.setEnabled(false);
        this.mnuInfGerenciales.setEnabled(false);
    }

    public void iniciarLog() {
        try {
            //String nombreLog = "C:\\KARU\\log\\log-" + new SimpleDateFormat("ddMMyy_HHmmss").format(new Date()) + ".log";
            //System.out.println("Nombre del log >>>>>>>>>>>>>> " + nombreLog);
            String nombreLog = "C:\\KARU\\log\\log.log";
            fh = new FileHandler(nombreLog);
            logger.addHandler(fh);
            SimpleFormatter formatter = new SimpleFormatter();
            fh.setFormatter(formatter);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al generar archivo log."
                    + "\n" + ex.getMessage(), "Principal", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void login() {
        Login login = new Login(this, true, em, logger);
        login.setResizable(false);
        login.setVisible(true);

        if (login.getEstado()) {
            this.setUsuario(login.getUsuarioLogueado());
            habilitarMenus();
        }
    }

    public boolean cerrarVentanas() {
        JInternalFrame[] activos = escritorio.getAllFrames();
        int i = 0;

        if (activos.length > 0) {
            int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Existen ventanas abiertas."
                    + "\n" + "Si desea continuar las mismas serán cerradas.",
                    "Cerrar Sessión.", JOptionPane.YES_NO_OPTION);
            if (showConfirmDialog == 0) {
                while (i < activos.length) {
                    activos[i].dispose();
                    i++;
                }
                return true;
            } else {
                return false;
            }
        } else {
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mantMnuClientes;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuCerrarSesion;
    private javax.swing.JMenu mnuConfiguracion;
    private javax.swing.JMenu mnuDatos;
    private javax.swing.JMenuItem mnuEstadiRanking;
    private javax.swing.JMenuItem mnuEstadoCuentaClientes;
    private javax.swing.JMenu mnuInfGerenciales;
    private javax.swing.JMenu mnuInformes;
    private javax.swing.JMenuItem mnuInformes_controlCaja;
    private javax.swing.JMenuItem mnuInformes_estadisiticas;
    private javax.swing.JMenuItem mnuIniciarSesion;
    private javax.swing.JMenuItem mnuListadoStock;
    private javax.swing.JMenuItem mnuProductos;
    private javax.swing.JMenuItem mnuReposicionDiaria;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenu mnuSistema;
    private javax.swing.JMenuItem mnuTipoProductos;
    private javax.swing.JMenu mnuVentas;
    private javax.swing.JMenuItem mnuVentasFacturacion;
    private javax.swing.JMenuItem mnuVentasPorVendedor;
    private javax.swing.JMenuItem mnu_acerca;
    private javax.swing.JMenuItem mnu_ajuste_stock;
    private javax.swing.JMenuItem mnu_configuracion;
    // End of variables declaration//GEN-END:variables
}
